export const assets = [
    {url: "./posible_protagonista.png", name: "myProta"},
    {url: "./Close_def.png", name: "closeDef"},
    {url: "./Close_down.png", name: "closeDown"},
    {url: "./Close_over.png", name: "closeOver"},
    {url: "./Leaderboard_def.png", name: "leaderboardDef"},
    {url: "./Leaderboard_down.png", name: "leaderboardDown"},
    {url: "./Leaderboard_over.png", name: "leaderboardOver"},
    {url: "./Play_def.png", name: "playDef"},
    {url: "./Play_down.png", name: "playDown"},
    {url: "./Play_over.png", name: "playOver"},
    {url: "./SaveReplay_def.png", name: "saveReplayDef"},
    {url: "./SaveReplay_down.png", name: "saveReplayDown"},
    {url: "./SaveReplay_over.png", name: "saveReplayOver"},
    {url: "./panel-border-005.png", name: "panelBorder"},
    {url: "./divider-fade-003.png", name: "dividerLine"},
    {url: "./panelScore.png", name: "scorePanel"},
    {url: "./Star_def.png", name: "starDef"},
    {url: "./good witch/RunAnimation1.png", name: "goodwitchrun1"},
    {url: "./good witch/RunAnimation2.png", name: "goodwitchrun2"},
    {url: "./good witch/RunAnimation3.png", name: "goodwitchrun3"},
    {url: "./good witch/RunAnimation4.png", name: "goodwitchrun4"},
    {url: "./good witch/RunAnimation5.png", name: "goodwitchrun5"},
    {url: "./good witch/RunAnimation6.png", name: "goodwitchrun6"},
    {url: "./good witch/RunAnimation7.png", name: "goodwitchrun7"},
    {url: "./good witch/RunAnimation8.png", name: "goodwitchrun8"},
    {url: "./good witch/RunAnimation9.png", name: "goodwitchrun9"},
    {url: "./good witch/RunAnimation10.png", name: "goodwitchrun10"},
    {url: "./good witch/RunAnimation11.png", name: "goodwitchrun11"},
    {url: "./good witch/RunAnimation12.png", name: "goodwitchrun12"},
    {url: "./good witch/RunAnimation13.png", name: "goodwitchrun13"},
    {url: "./good witch/RunAnimation14.png", name: "goodwitchrun14"},
    {url: "./good witch/RunAnimation15.png", name: "goodwitchrun15"},
    {url: "./good witch/RunAnimation16.png", name: "goodwitchrun16"},
    {url: "./backgrounds/background1.png", name:"background1"},
    {url: "./platforms/platform1.png", name:"platform1"},
    {url: "./good witch/jumpAnimation/JumpAnimation1.png", name:"jumpAnimation1"},
    {url: "./good witch/jumpAnimation/JumpAnimation2.png", name:"jumpAnimation2"},
    {url: "./good witch/jumpAnimation/JumpAnimation3.png", name:"jumpAnimation3"},
    {url: "./good witch/jumpAnimation/JumpAnimation4.png", name:"jumpAnimation4"},
    {url: "./good witch/jumpAnimation/JumpAnimation5.png", name:"jumpAnimation5"},
    {url: "./good witch/jumpAnimation/JumpAnimation6.png", name:"jumpAnimation6"},
    {url: "./good witch/jumpAnimation/JumpAnimation7.png", name:"jumpAnimation7"},
    {url: "./good witch/jumpAnimation/JumpAnimation8.png", name:"jumpAnimation8"},
    {url: "./good witch/jumpAnimation/JumpAnimation9.png", name:"jumpAnimation9"},
    {url: "./good witch/jumpAnimation/JumpAnimation10.png", name:"jumpAnimation10"},
    {url: "./good witch/jumpAnimation/JumpAnimation11.png", name:"jumpAnimation11"},
    {url: "./good witch/jumpAnimation/JumpAnimation12.png", name:"jumpAnimation12"},
    {url: "./good witch/jumpAnimation/JumpAnimation13.png", name:"jumpAnimation13"},
    {url: "./good witch/jumpAnimation/JumpAnimation14.png", name:"jumpAnimation14"},
    {url: "./good witch/jumpAnimation/JumpAnimation15.png", name:"jumpAnimation15"},
    {url: "./good witch/idleAnimation/IdleAnimation1.png", name:"idleAnimation1"},
    {url: "./good witch/idleAnimation/IdleAnimation2.png", name:"idleAnimation2"},
    {url: "./good witch/idleAnimation/IdleAnimation3.png", name:"idleAnimation3"},
    {url: "./good witch/idleAnimation/IdleAnimation4.png", name:"idleAnimation4"},
    {url: "./good witch/idleAnimation/IdleAnimation5.png", name:"idleAnimation5"},
    {url: "./good witch/idleAnimation/IdleAnimation6.png", name:"idleAnimation6"},
    {url: "./good witch/idleAnimation/IdleAnimation7.png", name:"idleAnimation7"},
    {url: "./good witch/idleAnimation/IdleAnimation8.png", name:"idleAnimation8"},
    {url: "./good witch/idleAnimation/IdleAnimation9.png", name:"idleAnimation9"},
    {url: "./good witch/idleAnimation/IdleAnimation10.png", name:"idleAnimation10"},
    {url: "./good witch/idleAnimation/IdleAnimation11.png", name:"idleAnimation11"},
    {url: "./good witch/idleAnimation/IdleAnimation12.png", name:"idleAnimation12"},
    {url: "./good witch/idleAnimation/idleAnimation13.png", name:"idleAnimation13"},
    {url: "./good witch/deathAnimation/deathAnimation1.png", name:"deathAnimation1"},
    {url: "./good witch/deathAnimation/deathAnimation2.png", name:"deathAnimation2"},
    {url: "./good witch/deathAnimation/deathAnimation3.png", name:"deathAnimation3"},
    {url: "./good witch/deathAnimation/deathAnimation4.png", name:"deathAnimation4"},
    {url: "./good witch/deathAnimation/deathAnimation5.png", name:"deathAnimation5"},
    {url: "./good witch/deathAnimation/deathAnimation6.png", name:"deathAnimation6"},
    {url: "./good witch/deathAnimation/deathAnimation7.png", name:"deathAnimation7"},
    {url: "./good witch/deathAnimation/deathAnimation8.png", name:"deathAnimation8"},
    {url: "./good witch/deathAnimation/deathAnimation9.png", name:"deathAnimation9"},
    {url: "./good witch/deathAnimation/deathAnimation.png", name:"deathAnimation10"},
    {url: "./good witch/attackAnimation/AttackAnimation1.png", name:"attackAnimation1"},
    {url: "./good witch/attackAnimation/AttackAnimation2.png", name:"attackAnimation2"},
    {url: "./good witch/attackAnimation/AttackAnimation3.png", name:"attackAnimation3"},
    {url: "./good witch/attackAnimation/AttackAnimation4.png", name:"attackAnimation4"},
    {url: "./good witch/attackAnimation/AttackAnimation5.png", name:"attackAnimation5"},
    {url: "./good witch/attackAnimation/AttackAnimation6.png", name:"attackAnimation6"},
    {url: "./good witch/attackAnimation/AttackAnimation7.png", name:"attackAnimation7"},
    {url: "./good witch/attackAnimation/AttackAnimation8.png", name:"attackAnimation8"},
    {url: "./good witch/attackAnimation/AttackAnimation9.png", name:"attackAnimation9"},
    {url: "./good witch/attackAnimation/AttackAnimation10.png", name:"attackAnimation10"},
    {url: "./objects/145.png", name:"manaPot"},


]
